---
- name: install tomcat9 server
  hosts: application
  become: yes
  vars:
    tomcat_name: tomcat
    tomcat_home: /opt/tomcat
    tomcat_shell: /bin/false
    tomcat_download_url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.70/bin/apache-tomcat-9.0.70.tar.gz
    tomcat_download_path: /tmp/apache-tomcat-9.0.70.tar.gz
  tasks:
    - name: update ubuntu 20.04 and install java 11
      ansible.builtin.apt:
        name: openjdk-11-jdk
        update_cache: yes
        state: present
    - name: creat a system user
      ansible.builtin.user:
        name: "{{ tomcat_name }}"
        home: "{{ tomcat_home }}"
        shell: "{{ tomcat_shell }}"
    - name: download tomcat tar file
      ansible.builtin.get_url:
        url: "{{ tomcat_download_url }}"
        dest: "{{ tomcat_download_path }}"
    - name: Extract the download file
      ansible.builtin.unarchive:
        src: "{{ tomcat_download_path }}"
        dest: "{{ tomcat_home }}"
        remote_src: yes

      