---
- name: install testing app
  hosts: app
  become: yes
  vars:
    utilities:
      - nano
      - tree
      - git
  tasks:    
    - name: install some important app
      ansible.builtin.apt:
        name: "{{ utilities }}"
        state: present